# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content1',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='content1',
            name='Name',
            field=models.CharField(max_length=300),
        ),
    ]
